/**
 * Daily Plan — Today's complete training plan.
 *
 * Generated by buildDailyPlan() — a pure function.
 * Contains ordered exercises with individual doses and rationale.
 *
 * The plan captures its own input snapshot so we can always
 * explain WHY these exercises were chosen.
 *
 * @module daily-plan
 */

import type { BodyProfile } from './body-profile';
import type { DailyState } from './daily-state';
import type { GolfContext, FocusMode } from './golf-context';
import type { Exercise, ExerciseDose } from './exercise';

// ---------------------------------------------------------------------------
// Exercise assignment
// ---------------------------------------------------------------------------

/** A single exercise assignment in today's plan */
export interface ExerciseAssignment {
  /** The exercise to perform */
  exercise: Exercise;

  /** Dose for this session (may differ from exercise.defaultDose) */
  dose: ExerciseDose;

  /** Order in the plan (1-based) */
  order: number;

  /** Why this exercise was chosen */
  rationale: { sv: string; en: string };

  /** Which finding(s) this addresses */
  addressesFindings: string[];

  /** Estimated duration in seconds */
  estimatedDurationSec: number;
}

// ---------------------------------------------------------------------------
// Category distribution
// ---------------------------------------------------------------------------

/** How the plan's time is distributed across categories */
export interface PlanDistribution {
  /** Percentage of time spent on mobility */
  mobilityPercent: number;

  /** Percentage of time spent on motor control */
  controlPercent: number;

  /** Percentage of time spent on strength/load tolerance */
  strengthPercent: number;

  /** Percentage of time spent on recovery */
  recoveryPercent: number;
}

// ---------------------------------------------------------------------------
// Daily Plan (the main entity)
// ---------------------------------------------------------------------------

/** Today's complete training plan */
export interface DailyPlan {
  /** Unique plan ID */
  id: string;

  /** When this plan was generated */
  createdAt: Date;

  /** The input that generated this plan (for traceability) */
  input: {
    /** Snapshot of profile at generation time */
    profileSnapshot: BodyProfile;
    /** Today's state */
    state: DailyState;
    /** Today's context */
    context: GolfContext;
  };

  /** Assigned exercises in execution order */
  exercises: ExerciseAssignment[];

  /** Total estimated duration in minutes */
  totalMinutes: number;

  /** Overall focus description */
  focusSummary: { sv: string; en: string };

  /** Human-readable rationale for the entire plan */
  rationale: { sv: string; en: string };

  /** Category distribution breakdown */
  distribution: PlanDistribution;

  /** Whether safety mode was activated (due to pain) */
  safetyModeActive: boolean;

  /** If safety mode, what adjustments were made */
  safetyAdjustments: string[];
}
